services:
  sw_team_1-backend-blue:
    image: sw_team_1-backend:latest
    container_name: sw_team_1-backend-blue
    ports:
      - "8080:8080"

  sw_team_1-frontend:
    image: sw_team_1-frontend:latest
    container_name: sw_team_1-frontend
    ports:
      - "3000:80"

  sw_team_1-nginx:
    image: nginx:alpine
    container_name: sw_team_1-nginx
    ports:
      - "8002:8002"
    volumes:
      # 디렉토리 단위 마운트 (파일 단위 마운트는 sed -i / docker cp 등 rename 불가)
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - sw_team_1-backend-blue
      - sw_team_1-frontend
