pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh "./gradlew sonar"
                sh './gradlew clean build'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                    ./gradlew sonar \
                      -Dsonar.projectKey=onpremise-devops \
                      -Dsonar.host.url=http://서버IP:8000 \
                      -Dsonar.login=$SONAR_AUTH_TOKEN
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}