pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                    // backend 폴더로 이동해서 작업 수행
                    dir('backend') {
                        // 실행 권한 부여 후 빌드 및 소나큐브 실행
                        sh 'chmod +x gradlew'
                        sh './gradlew sonar'
                    }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                    ./gradlew sonar \
                      -Dsonar.projectKey=streaming-chat \
                      -Dsonar.host.url=http://http://172.21.33.69:8000 \
                      -Dsonar.login=$SONAR_AUTH_TOKEN
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}